"""
Input Choice Catalog for Methane Isotope Box Models
=====================================================
Every scientific choice is documented with literature references.
Modify DEFAULT_CONFIG or use SENSITIVITY_PRESETS for tests.

Taxonomy of inputs:
  A. Atmospheric observations (δ¹³C, δD, CH₄)
  B. Source end-member signatures (FF, Mic, BB — both isotopes)
  C. Sink KIE values (OH, Cl, Strat, Soil — both isotopes)
  D. Sink fractional contributions
  E. Methane lifetime
  F. Biomass-burning emissions (for 2×2 models where BB is fixed)
  G. Hemispheric parameters (for two-box models)
"""

# ═══════════════════════════════════════════════════════════════════════════
# A. ATMOSPHERIC OBSERVATIONS
# ═══════════════════════════════════════════════════════════════════════════
# Not configurable per se — these are the measured data files.
# Listed here for documentation / future swapability.
ATM_OBS_CATALOG = {
    'CH4_global': {
        'file': 'GML_CH4_AnnualMean.xlsx',
        'ref': 'Lan et al. (2024), NOAA GML',
        'note': 'Global annual mean CH₄ mixing ratio (ppb)',
    },
    'd13C_hemispheric': {
        'file': 'ch4c13_nh_sh_mean.xlsx',
        'ref': 'White et al. (2023), INSTAAR/NOAA',
        'note': 'NH and SH δ¹³C-CH₄ monthly means',
    },
    'd13C_MC_iterations': {
        'file': 'd13C_dei_compiled.txt',
        'ref': 'Bao et al. (this work), compiled from INSTAAR DEI',
        'note': '1000 MC realisations of global annual δ¹³C-CH₄',
    },
    'dD_global_umezawa': {
        'file': 'GlobMean_dD_iterations_UmezawaCal_noBUDS.xlsx',
        'ref': 'Umezawa et al. (2012, JGR); Rice et al. (2016)',
        'note': 'Global mean δD-CH₄ MC iterations, Umezawa calibration, no BUDS',
    },
    'dD_global_improved': {
        'file': None,  # generated by improved_dD_pipeline.py
        'ref': 'This work; area-weighted cf. Riddell-Young et al. (2025, PNAS)',
        'note': 'Area-weighted global δD-CH₄ with cosine-lat + bootstrap',
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# B. SOURCE END-MEMBER SIGNATURES
# ═══════════════════════════════════════════════════════════════════════════
FF_SIGNATURE_OPTIONS = {
    'EDGAR': {
        'd13C_file': 'FF_d13C_GlobMC_EDGAR.csv',
        'dD_file': 'FF_dD_GlobMC_EDGAR.csv',
        'ref': 'Sherwood et al. (2017, ESSD); EDGAR v8.0 category weighting',
        'note': 'EDGAR-inventory-weighted global FF δ values, 1000 MC columns',
    },
    'CTCH4': {
        'd13C_file': 'FF_d13C_GlobMC_CTCH4.csv',
        'dD_file': 'FF_dD_GlobMC_CTCH4.csv',
        'ref': 'Bruhwiler et al. (2014); CarbonTracker-CH₄ posterior weighting',
        'note': 'CT-CH₄ posterior-weighted global FF δ values, 1000 MC columns',
    },
    'GlobUnc': {
        'd13C_file': 'FF_d13C_GlobUnc.csv',
        'dD_file': 'FF_dD_GlobUnc.csv',
        'ref': 'Sherwood et al. (2017, ESSD)',
        'note': 'Global mean ± uncertainty (not MC), used as fallback',
    },
}

MIC_DD_UNCERTAINTY_OPTIONS = {
    'original_7': {
        'value': 7.0,
        'ref': 'Bao et al. (this work), original estimate',
    },
    'riddell_young_8.2': {
        'value': 8.2,
        'ref': 'Riddell-Young et al. (2025, PNAS) Table 1',
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# C. SINK KIE VALUES
# ═══════════════════════════════════════════════════════════════════════════
KIE_OPTIONS = {
    # --- OH + ¹³C ---
    'OH_13C': {
        'cantrell': {
            'dist': 'fixed', 'value': 1.0054,
            'ref': 'Cantrell et al. (1990, JGR)',
        },
        'saueressig': {
            'dist': 'fixed', 'value': 1.0039,
            'ref': 'Saueressig et al. (2001, JGR)',
        },
        'sampled': {
            'dist': 'uniform', 'low': 1.0039, 'high': 1.0054,
            'ref': 'Literature range: Saueressig (2001) – Cantrell (1990)',
        },
    },
    # --- OH + D ---
    'OH_D': {
        'saueressig': {
            'dist': 'fixed', 'value': 1.294,
            'ref': 'Saueressig et al. (2001, JGR)',
        },
        'whitehill': {
            'dist': 'fixed', 'value': 1.327,
            'ref': 'Whitehill-Joelson average',
        },
        'sampled': {
            'dist': 'uniform', 'low': 1.294, 'high': 1.327,
            'ref': 'Literature range: Saueressig (2001) – Whitehill-Joelson',
        },
    },
    # --- Cl + ¹³C ---
    'Cl_13C': {
        'sampled': {
            'dist': 'normal', 'mean': 1.066, 'std': 0.002,
            'ref': 'Saueressig et al. (1995, GRL)',
        },
    },
    # --- Cl + D ---
    'Cl_D': {
        'sampled': {
            'dist': 'normal', 'mean': 1.52, 'std': 0.02,
            'ref': 'Saueressig et al. (2001, JGR)',
        },
    },
    # --- Stratosphere + ¹³C ---
    'Strat_13C': {
        'fixed': {
            'dist': 'fixed', 'value': 1.003,
            'ref': 'Saueressig et al. (2001); Lassey et al. (2007, ACP)',
        },
        'sampled': {
            'dist': 'normal', 'mean': 1.003, 'std': 0.001,
            'ref': 'Dyonisius et al. (2020, Nature); Lassey (2007)',
        },
    },
    # --- Stratosphere + D ---
    'Strat_D': {
        'fixed': {
            'dist': 'fixed', 'value': 1.179,
            'ref': 'Dyonisius et al. (2020, Nature); Beck et al. (2018)',
        },
        'sampled': {
            'dist': 'normal', 'mean': 1.179, 'std': 0.01,
            'ref': 'Beck et al. (2018); Dyonisius et al. (2020)',
        },
    },
    # --- Soil + ¹³C ---
    'Soil_13C': {
        'fixed': {
            'dist': 'fixed', 'value': 1.0201,
            'ref': 'Average: Snover & Quay (2000); Tyler et al. (1994); Reeburgh et al. (1997)',
        },
        'sampled': {
            'dist': 'normal', 'mean': 1.0201, 'std': 0.003,
            'ref': 'Snover & Quay (2000) ± ecosystem variability',
        },
    },
    # --- Soil + D ---
    'Soil_D': {
        'fixed': {
            'dist': 'fixed', 'value': 1.083,
            'ref': 'Snover & Quay (2000, GBC)',
        },
        'sampled': {
            'dist': 'normal', 'mean': 1.083, 'std': 0.01,
            'ref': 'Snover & Quay (2000)',
        },
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# D. SINK FRACTIONAL CONTRIBUTIONS
# ═══════════════════════════════════════════════════════════════════════════
SINK_FRACTION_OPTIONS = {
    'global_default': {
        'OH': 0.835, 'Cl': 0.035, 'Strat': 0.07, 'Soil': 0.06,
        'ref': 'CarbonTracker documentation; composite',
    },
    'thanwerdas': {
        'OH': 0.899, 'Cl': 0.006, 'Strat': 0.03, 'Soil': 0.065,
        'ref': 'Thanwerdas et al. (2024, ACP)',
    },
    # Hemispheric (for two-box models)
    'NH_default': {
        'OH': 0.825, 'Cl': 0.040, 'Strat': 0.070, 'Soil': 0.065,
        'ref': 'Estimated: higher Cl in NH tropics, more soil uptake boreal',
    },
    'SH_default': {
        'OH': 0.850, 'Cl': 0.028, 'Strat': 0.070, 'Soil': 0.052,
        'ref': 'Estimated: lower Cl, less land area for soil sink',
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# E. METHANE LIFETIME
# ═══════════════════════════════════════════════════════════════════════════
LIFETIME_OPTIONS = {
    'fixed_9yr': {
        'mode': 'fixed', 'value': 9.0,
        'ref': 'IPCC AR5/AR6 central estimate; Prather et al. (2012)',
    },
    'time_varying_he2026': {
        'mode': 'linear', 'tau0': 9.0, 'slope': -0.017, 'ref_year': 2010,
        'ref': 'He et al. (2026, Science): TROPOMI-derived OH trend',
        'note': 'τ(t) = 9.0 − 0.017×(t−2010). Gives τ(1999)=9.19, τ(2022)=8.80',
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# F. BIOMASS-BURNING EMISSIONS (for 2×2 models)
# ═══════════════════════════════════════════════════════════════════════════
BB_OPTIONS = {
    'CT_GFED4_mean': {
        'mode': 'fixed_global_mean',
        'ref': 'CarbonTracker-CH₄; GFED4 prior (van der Werf et al., 2017)',
    },
    'CT_GFED4_annual': {
        'mode': 'time_varying',
        'ref': 'CarbonTracker-CH₄; GFED4 annual prior',
    },
    'declining': {
        'mode': 'declining',
        'end_fraction': 0.09,
        'ref': 'Sensitivity test: declining BB (cf. Worden et al., 2017)',
    },
}

# ═══════════════════════════════════════════════════════════════════════════
# G. HEMISPHERIC PARAMETERS (for two-box models)
# ═══════════════════════════════════════════════════════════════════════════
HEMISPHERIC_OPTIONS = {
    'IH_gradient_ppb': {
        'default': {'start': 80, 'end': 100},
        'ref': 'NOAA GML NH-SH gradient; Dlugokencky et al. (2011)',
    },
    'dD_IH_offset': {
        'v3.0_old': {'value': 1.5, 'ref': 'Original v3.0 estimate (too small)'},
        'riddell_young': {'value': 6.0,
            'ref': 'Riddell-Young et al. (2025, PNAS): NH δD ~12‰ lower than SH',
        },
    },
    'tau_ex': {
        'fixed_1yr': {'mode': 'fixed', 'value': 1.0,
            'ref': 'Patra et al. (2011, ACP); Naus et al. (2019)'},
        'sampled': {'mode': 'normal', 'mean': 1.0, 'std': 0.1,
            'ref': 'Patra et al. (2011) ± transport model spread'},
    },
    'lifetime_ratio': {
        'NH': 0.95, 'SH': 1.05,
        'ref': 'Shorter τ in NH (more OH); cf. Lawrence et al. (2001)',
    },
    'BB_NH_SH_split': {
        'GFED4': {'NH': 0.55, 'SH': 0.45},
        'ref': 'van der Werf et al. (2017), GFED4 fire distribution',
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# DEFAULT CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════
DEFAULT_CONFIG = {
    # Monte Carlo
    'n_iterations': 1000,
    'seed': 42,

    # Source signatures
    'FF_signature': 'EDGAR',       # 'EDGAR' | 'CTCH4' | 'GlobUnc'
    'mic_dD_uncertainty': 8.2,     # ‰ — Riddell-Young (2025)

    # KIE selections (key → chosen option name from KIE_OPTIONS)
    'KIE': {
        'OH_13C':    'sampled',    # uniform(1.0039, 1.0054)
        'OH_D':      'sampled',    # uniform(1.294, 1.327)
        'Cl_13C':    'sampled',    # normal(1.066, 0.002)
        'Cl_D':      'sampled',    # normal(1.52, 0.02)
        'Strat_13C': 'sampled',    # normal(1.003, 0.001)
        'Strat_D':   'sampled',    # normal(1.179, 0.01)
        'Soil_13C':  'sampled',    # normal(1.0201, 0.003)
        'Soil_D':    'sampled',    # normal(1.083, 0.01)
    },

    # Sink fractions
    'sink_fractions_global': 'global_default',  # for one-box
    'sink_fractions_NH': 'NH_default',          # for two-box
    'sink_fractions_SH': 'SH_default',          # for two-box

    # Lifetime
    'lifetime': 'time_varying_he2026',

    # BB (for 2×2 models)
    'BB_mode': 'CT_GFED4_mean',

    # Hemispheric (for two-box models)
    'dD_IH_offset': 6.0,           # ‰ — Riddell-Young (2025)
    'tau_ex_mode': 'sampled',       # 'fixed_1yr' | 'sampled'
    'IH_gradient_start': 80,       # ppb
    'IH_gradient_end': 100,        # ppb
    'BB_NH_fraction': 0.55,
    'BB_SH_fraction': 0.45,
    'lifetime_ratio_NH': 0.95,
    'lifetime_ratio_SH': 1.05,
}


# ═══════════════════════════════════════════════════════════════════════════
# SENSITIVITY PRESETS
# ═══════════════════════════════════════════════════════════════════════════
def _merge(base, overrides):
    """Deep-merge overrides into a copy of base."""
    import copy
    cfg = copy.deepcopy(base)
    for k, v in overrides.items():
        if isinstance(v, dict) and isinstance(cfg.get(k), dict):
            cfg[k].update(v)
        else:
            cfg[k] = v
    return cfg


SENSITIVITY_PRESETS = {
    'default': DEFAULT_CONFIG,

    # --- KIE sensitivity ---
    'cantrell_only': _merge(DEFAULT_CONFIG, {
        'KIE': {**DEFAULT_CONFIG['KIE'],
                'OH_13C': 'cantrell', 'OH_D': 'whitehill'},
    }),
    'saueressig_only': _merge(DEFAULT_CONFIG, {
        'KIE': {**DEFAULT_CONFIG['KIE'],
                'OH_13C': 'saueressig', 'OH_D': 'saueressig'},
    }),
    'KIE_strat_soil_fixed': _merge(DEFAULT_CONFIG, {
        'KIE': {**DEFAULT_CONFIG['KIE'],
                'Strat_13C': 'fixed', 'Strat_D': 'fixed',
                'Soil_13C': 'fixed', 'Soil_D': 'fixed'},
    }),

    # --- Lifetime sensitivity ---
    'fixed_lifetime': _merge(DEFAULT_CONFIG, {
        'lifetime': 'fixed_9yr',
    }),

    # --- FF signature sensitivity ---
    'CTCH4_FF': _merge(DEFAULT_CONFIG, {
        'FF_signature': 'CTCH4',
    }),

    # --- Mic δD uncertainty ---
    'mic_dD_7': _merge(DEFAULT_CONFIG, {
        'mic_dD_uncertainty': 7.0,
    }),

    # --- BB sensitivity (2×2 only) ---
    'BB_annual': _merge(DEFAULT_CONFIG, {
        'BB_mode': 'CT_GFED4_annual',
    }),
    'BB_declining': _merge(DEFAULT_CONFIG, {
        'BB_mode': 'declining',
    }),

    # --- Sink fraction sensitivity ---
    'thanwerdas_sinks': _merge(DEFAULT_CONFIG, {
        'sink_fractions_global': 'thanwerdas',
    }),

    # --- Hemispheric sensitivity ---
    'tau_ex_fixed': _merge(DEFAULT_CONFIG, {
        'tau_ex_mode': 'fixed_1yr',
    }),
    'dD_offset_old': _merge(DEFAULT_CONFIG, {
        'dD_IH_offset': 1.5,
    }),
}
